# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='address',
            new_name='art',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='address2',
            new_name='course_duration',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='last_name',
            new_name='course_title',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='city',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='first_name',
            new_name='instructor',
        ),
    ]
