# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20160217_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_duration',
        ),
    ]
