# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20160217_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.CharField(choices=[(b'2', b'2 Weeks'), (b'8', b'8 Weeks')], default=b'2', max_length=25),
        ),
    ]
