# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='art',
            field=models.ImageField(default=b'/uploads/hello.png', upload_to=b'static/uploads'),
        ),
    ]
