# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20160217_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='art',
            field=models.ImageField(upload_to=b'static/uploads'),
        ),
    ]
