# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:30
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20160217_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from=b'course_title'),
            preserve_default=False,
        ),
    ]
